### ISSUE TITLE
Document creating the ID of the sent message

### ISSUE THREAD

**Issue by KrzysztofMadejski** [Rhymen/go-whatsapp#101]
- [ ] In the README and examples
- [ ] expose [the code of creating WhatsApp-like ID](https://github.com/Rhymen/go-whatsapp/blob/master/message.go#L140-L142) as an exported function

Re #43

**Comment by KrzysztofMadejski** [comment]
BTW: I'm up for help/contributing, but I would need a green light or suggestions on how to implement things.

**Comment by SchulteMK** [comment]
@KrzysztofMadejski Hi, help is always appreciated:)
Exposing that function would be nice idea to help the user. I'm not at my workstation at the moment, so that could be your first little contribution. If you create a PR, I will approve it bretty quickly.

In general some of the functions inside the contact.go are pretty rudimentary implemented and return a `<-chan string`. The string from the channel (if any) is a json marshalled object. Each function should return their own struct with all information from the json inside. Another good way of helping would be to answer some of the open issues and try to help the community. Often it is pretty hard to reproduce some of the errors, so help is very much appreciated.
