### ISSUE TITLE
The legality of using the Whatsapp API

### ISSUE THREAD

**Issue by carloslfu** [Rhymen/go-whatsapp#342]
Hi everyone, I used this project a couple of times, but now a client is asking me about the legality concerns. Does someone have any idea about this topic? is it legal to use the Whatsapp API this way? Thanks in advance!

**Comment by codenoid** [comment]
this libary **illegally** use whatsapp api

**Comment by beshoo** [comment]
Why it is illegal? You are using the browser method which provided by WhatsApp...

Show me in tbe term of use any part that said this is illegal....

**Comment by tulir** [comment]
It's probably against the terms of service, but breaking terms of service is not illegal.

WhatsApp could definitely ban users though. They actually do ban people using the client API through unofficial libraries (like [yowsup](https://github.com/tgalal/yowsup)), but they don't seem to care about unofficial web app API users (like go-whatsapp and other [whatsapp-web-reveng](https://github.com/sigalor/whatsapp-web-reveng)-based projects). I don't have any idea why, perhaps because it still requires everyone to have the official app installed.

**Comment by beshoo** [comment]
The yowsup is using the private API, which is 100% not right approach

**Comment by beshoo** [comment]
>WhatsApp could definitely ban users though. They actually do ban people using the client API through unofficial libraries (like yowsup)

I am not sure if WhatsApp can ban soket approach since we are using the Web service which they approved to be used via browser. 

Now, WhatsApp can not read messages (at least that what they said) 

But the can ban if you abuse sending a lot of messages no stop...
If a lot of blocks you had and report as well. 

But ban the WhatsApp web approach, well i have my doubts. 

Regard
