### ISSUE TITLE
Check if number has WhatsApp

### ISSUE THREAD

**Issue by Mikolasek93** [Rhymen/go-whatsapp#35]
Hi,
is it possible to check whether number has WhatsApp or not? 

Because right now, I can send message to non existing numbers, which leads to fail of mobile application when you click on wrong number conversation on your phone.

Thanks a lot!

**Comment by tkovs** [comment]
Really useful

**Comment by MaiaVinicius** [comment]
It seems that this issue is connected with the #36 issue. If the app is able to get the message status (_not sent, sent, delivered or seen_) we can have access to:

- Know if a message was delivered (_message status = delivered_)
- Know if a message was seen (_message status = seen_)
- Know if a message was not sent. **Probably the user has no WhatsApp** (_message status = not sent - the clock icon)_

**Comment by Mikolasek93** [comment]
Yeah sure, i know about that feature, but my question was, if its possible WITHOUT sending message. Also, if number does not have whatsapp, message is still sent to WhatsApp servers.
Thank you!

**Comment by masterhacker382** [comment]
i can active any number wa
