### ISSUE TITLE
delay whatsapp business 

### ISSUE THREAD

**Issue by Leonardo-Crespo** [Rhymen/go-whatsapp#432]
I have a problem, I have some customers who are with a long delay when sending messages, would anyone know to inform me if there is something specific causing this problem?
obs: this is happening only with whtsapp business

**Comment by beshoo** [comment]
It is 90% related to the WhatsApp connectivity.
Internet speed and the mobile avaliableity.

Try it by your self, debug and see the out come.

Regard

**Comment by Leonardo-Crespo** [comment]
I don't think I formulated my question well. After using a service of mine with this api, some whatsapp applications from some companies that use our service, got delayed in their app, whatsapp was completely unstable.

**Comment by albertord84** [comment]
I'm having the same problem @Leonardo-Crespo related and now I'm surprised because it's just business account too... I have the last go-WhatsApp version... 

Some times it happen with normals WhatsApp numbers too but the problem goon quickly...

Do Somebody use business account with no problems?

Thanks! :)

**Comment by medinash** [comment]
I have the same problem. Whenever my client scans qrcode on my system, the same problem starts. Some messages are even sent, but to receive, it is only with 1 check .... Minutes later it arrives.

There is always this delay when receiving and sending messages. Apparently it is not a configuration on the phone, it only happens when you scan the qrcode via api.

**Comment by beshoo** [comment]
It is not related to the API, not the Whatsapp.
It is 100% related to the connectivity and the type of client mobile.

Let me explain why
If your client mobile chines mobile as Xiaomi or HUAWEI. those brands use to kill background prosses so you will end with send timeout.
Ask your client to connect his mobile to the charger! this will disable the DOS mode wich android apply when the mobile is not connected to the charger, some brands more aggressive than Google. to save battery

**Comment by beshoo** [comment]
Moreover, this case needs more logs, which I advice you to do, is to show us the log of the Go API, 
The type of your client mobile, intent stability, all these situations may results to send timeout.  
Remember that API dos did not send anything to Whatsapp, There is a SOKET between the API and the mobile, 
Mobile is who sends the message to the Whatsapp server!
