### ISSUE TITLE
Unexpected websocket close

### ISSUE THREAD

**Issue by hiwaleakshay** [Rhymen/go-whatsapp#98]
why i always keep getting this error?
`error caught in handler: unexpected websocket close: websocket: close 1006 (abnormal closure): unexpected EOF`
anyone else facing same issue? device is connected to internet and whatsapp is running too. 
didnt get this error until now.
I get this after about 7 to 8 mins on running program.

**Comment by rreuvekamp** [comment]
The problem seems to be on line:

https://github.com/Rhymen/go-whatsapp/blob/c9a81e9578840e5c04c49c9e6126a1682faf22fc/conn.go#L276

I propose it should reconnect if it detects the connection is closed, instead of trying to re-read from a closed connection every second.

After a while, I get a panic which says:

```
[Feb 13, 2019 11:44:08] unexpected websocket close: websocket: close 1000 (normal)
panic: repeated read on failed websocket connection

goroutine 105 [running]:
github.com/gorilla/websocket.(*Conn).NextReader(0xc00027c000, 0xf44680, 0xc000411312, 0x2, 0xc00041c600, 0xc000258180)
	/go/pkg/mod/github.com/gorilla/websocket@v1.4.0/conn.go:967 +0x356
github.com/gorilla/websocket.(*Conn).ReadMessage(0xc00027c000, 0x9ff740, 0xc0002201e0, 0x1, 0x1, 0xb3e060, 0xc0002201e0)
	/go/pkg/mod/github.com/gorilla/websocket@v1.4.0/conn.go:1028 +0x2f
github.com/Rhymen/go-whatsapp.(*Conn).readPump(0xc000219ad0)
	/go/pkg/mod/github.com/!rhymen/go-whatsapp@v0.0.0-20181218094654-2ca6af00572c/conn.go:272 +0x73
created by github.com/Rhymen/go-whatsapp.NewConn
	/go/pkg/mod/github.com/!rhymen/go-whatsapp@v0.0.0-20181218094654-2ca6af00572c/conn.go:129 +0x1ff
```

**Comment by hiwaleakshay** [comment]
@rreuvekamp Exactly. It should reconnect but after some time i see socket close and i have to rescan the qr code. Didnt encounter this problem but all of sudden i start getting this error.
@Rhymen Please look into this.

**Comment by bottookku** [comment]
i have the same problem how to solve it?

**Comment by hiwaleakshay** [comment]
@bottookku I removed all go-whatsapp files and reinstalled it. Also restarted my laptop. This solved for me.

**Comment by bottookku** [comment]
but my bug not solved reinstall files. what OS you using with this? and what phone i use android or this problems not dependencies from phone? i trying launch golang in windows and linux all that the same.

**Comment by tulir** [comment]
Could this be caused by c9a81e9578840e5c04c49c9e6126a1682faf22fc? I'm pretty sure it's something recent as reverting to an older version of my software that used 2ca6af00572c works fine, whereas the latest version doesn't. I haven't bisected the problem yet, but I couldn't see anything else obvious in the recent commits that could cause this.

**Comment by hiwaleakshay** [comment]
#106 
Lets continue discussion on this issue here. I am closing this for now.

**Comment by meodemsao** [comment]
i have the same problem with traefik 1.7.11

**Comment by imShara** [comment]
Still here

**Comment by TheCadu** [comment]
Same here... I don't know what happened... I tried find but no lucky.
