### ISSUE TITLE
Multiple whatsapp sessions

### ISSUE THREAD

**Issue by danielkrik** [Rhymen/go-whatsapp#99]
I need a hint of the best way to handle multiple whatsapp sessions (each one for a different whatsapp identifier), in other words, we have to work with a inconstant amount of whatsapp sessions.

Does this lib work fine with multiple whatsapps? Would it be necessary to create an instance for each one (running on different server ports)?

**Comment by SchulteMK** [comment]
I have not testet that, but it should be totally fine to create multiple connections to whatsapp with different phone numbers. I can't determine the best way to keep track of them, because it depends on your use case.

A quick suggestion on top of my head would be to use struct embedding: 
```
type waWrapper struct {
	*whatsapp.Conn
	identifier string
}
```
This way the `waWrapper` is a `*whatsapp.Conn`. Now you could define the `Handler` interface on the `waWrapper` and add it to itself like:

```
wac, err := whatsapp.NewConn(5 * time.Second)
if err != nil {...}
wrapper := &waWrapper{Conn: wac, identifier : "MyName"}
wrapper.AddHandler(wrapper)
```
Now you can access the whatsapp connection and the identifier from inside the handler. That way you should be able to process incoming messages and react to them. And for sending messages yourself that do not react on incoming messages I would simply create a map like `map[string]*waWrapper`.
Always use pointers to the `waWrapper` to not get in trouble with weird copies and incosistent state.

**Comment by dimaskiddo** [comment]
Already implemented in [dimaskiddo/go-whatsapp-rest](https://github.com/dimaskiddo/go-whatsapp-rest) you can see how it works in the helper file mostly it's the same like **Schulte** said, but this also still need some test :)

Hope this helps you also

**Comment by tarikhagustia** [comment]
thanks @dimaskiddo for sharing your repository anyway can you provide for documentation how to run it ? for your repository

**Comment by dimaskiddo** [comment]
sorry if my repo still doesn't have readme, prequisites:
- Make sure already install make and dep
- Create a workspace directory and export it as one of GOPATH directory
- Pull the repo under workspace directory in src/github.com/dimaskiddo/go-whatsapp-rest

How to run it:
- make go-dep-ensure
- make go-run

**Comment by SchulteMK** [comment]
I will close the issue now. For further questions regarding the use of [dimaskiddo/go-whatsapp-rest](https://github.com/dimaskiddo/go-whatsapp-rest) please open an issue over there.
